//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConveyorDoc.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConveyorDoc.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add by Cimco.
        /// </summary>
        public static string AddCimco {
            get {
                return ResourceManager.GetString("AddCimco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding item.
        /// </summary>
        public static string AddingItem {
            get {
                return ResourceManager.GetString("AddingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angles.
        /// </summary>
        public static string Angles {
            get {
                return ResourceManager.GetString("Angles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Theme.
        /// </summary>
        public static string ApplicationTheme {
            get {
                return ResourceManager.GetString("ApplicationTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Instruction.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run same task while other is still running!.
        /// </summary>
        public static string AppTaskErrorMultipleTask {
            get {
                return ResourceManager.GetString("AppTaskErrorMultipleTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want remove this item?.
        /// </summary>
        public static string AreYouSureYouWantRemoveThisItem {
            get {
                return ResourceManager.GetString("AreYouSureYouWantRemoveThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current record is busy by another user.
        /// </summary>
        public static string BusyRecord {
            get {
                return ResourceManager.GetString("BusyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change language you have to restart application!.
        /// </summary>
        public static string ChangeLanguageInfo {
            get {
                return ResourceManager.GetString("ChangeLanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing window size.
        /// </summary>
        public static string ChangingWindowSize {
            get {
                return ResourceManager.GetString("ChangingWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cimco is already connected.
        /// </summary>
        public static string CimcoConnectionInfo {
            get {
                return ResourceManager.GetString("CimcoConnectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cimco database is connected.
        /// </summary>
        public static string ConnectedCimcoToolTip {
            get {
                return ResourceManager.GetString("ConnectedCimcoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting Cimco database.
        /// </summary>
        public static string ConnectingCimcoDatabase {
            get {
                return ResourceManager.GetString("ConnectingCimcoDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to databases.
        /// </summary>
        public static string ConnectingToDatabases {
            get {
                return ResourceManager.GetString("ConnectingToDatabases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conveyor.
        /// </summary>
        public static string Conveyor {
            get {
                return ResourceManager.GetString("Conveyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conveyor Database.
        /// </summary>
        public static string ConveyorDatabase {
            get {
                return ResourceManager.GetString("ConveyorDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conveyor Module.
        /// </summary>
        public static string ConveyorModule {
            get {
                return ResourceManager.GetString("ConveyorModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create date:.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by:.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added successfully to database.
        /// </summary>
        public static string CrudAddInfo {
            get {
                return ResourceManager.GetString("CrudAddInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutting part.
        /// </summary>
        public static string CuttingPart {
            get {
                return ResourceManager.GetString("CuttingPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database path.
        /// </summary>
        public static string DatabasePath {
            get {
                return ResourceManager.GetString("DatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum (DT).
        /// </summary>
        public static string DatumDT {
            get {
                return ResourceManager.GetString("DatumDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decanter database.
        /// </summary>
        public static string DecanterDatabase {
            get {
                return ResourceManager.GetString("DecanterDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decanter Module.
        /// </summary>
        public static string DecanterModule {
            get {
                return ResourceManager.GetString("DecanterModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decanter Size.
        /// </summary>
        public static string DecanterSize {
            get {
                return ResourceManager.GetString("DecanterSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate GetAll must be implemented.
        /// </summary>
        public static string DelegateGetAllError {
            get {
                return ResourceManager.GetString("DelegateGetAllError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting record.
        /// </summary>
        public static string DeletingRecord {
            get {
                return ResourceManager.GetString("DeletingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot empty.
        /// </summary>
        public static string DescriptionCannotEmpty {
            get {
                return ResourceManager.GetString("DescriptionCannotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Database.
        /// </summary>
        public static string DescriptionDatabase {
            get {
                return ResourceManager.GetString("DescriptionDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriptions.
        /// </summary>
        public static string Descriptions {
            get {
                return ResourceManager.GetString("Descriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Tools.
        /// </summary>
        public static string DetailedTools {
            get {
                return ResourceManager.GetString("DetailedTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dialog content must be a Framework Element.
        /// </summary>
        public static string DialogContentFrameworkElementError {
            get {
                return ResourceManager.GetString("DialogContentFrameworkElementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        public static string Directories {
            get {
                return ResourceManager.GetString("Directories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cimco database is disconnected.
        /// </summary>
        public static string DisconnectedCimcoToolTip {
            get {
                return ResourceManager.GetString("DisconnectedCimcoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawings.
        /// </summary>
        public static string Drawings {
            get {
                return ResourceManager.GetString("Drawings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing Templates.
        /// </summary>
        public static string DrawingTemplates {
            get {
                return ResourceManager.GetString("DrawingTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing Variables.
        /// </summary>
        public static string DrawingVariables {
            get {
                return ResourceManager.GetString("DrawingVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droping nc program.
        /// </summary>
        public static string DropingNcProgram {
            get {
                return ResourceManager.GetString("DropingNcProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DXF Templates.
        /// </summary>
        public static string DXFTemplates {
            get {
                return ResourceManager.GetString("DXFTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Fixture.
        /// </summary>
        public static string EditFixture {
            get {
                return ResourceManager.GetString("EditFixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en_US {
            get {
                return ResourceManager.GetString("en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter drawing templates directory.
        /// </summary>
        public static string EnterDrawingTemplatesDirecotry {
            get {
                return ResourceManager.GetString("EnterDrawingTemplatesDirecotry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter fixtures workspace directory.
        /// </summary>
        public static string EnterFixturesWorkspaceDirectory {
            get {
                return ResourceManager.GetString("EnterFixturesWorkspaceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create new instruction. Empty fields.
        /// </summary>
        public static string ErrorInstructionValidation {
            get {
                return ResourceManager.GetString("ErrorInstructionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Remove you have to select word file.
        /// </summary>
        public static string ErrorUnSelectedWordFile {
            get {
                return ResourceManager.GetString("ErrorUnSelectedWordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace.
        /// </summary>
        public static string FixtureCommandBar_Workspace {
            get {
                return ResourceManager.GetString("FixtureCommandBar_Workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixture Database.
        /// </summary>
        public static string FixtureDatabase {
            get {
                return ResourceManager.GetString("FixtureDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixtures data .
        /// </summary>
        public static string FixtureFolder {
            get {
                return ResourceManager.GetString("FixtureFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixture number.
        /// </summary>
        public static string FixtureNumber {
            get {
                return ResourceManager.GetString("FixtureNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixtures.
        /// </summary>
        public static string Fixtures {
            get {
                return ResourceManager.GetString("Fixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixtures Database.
        /// </summary>
        public static string FixturesDatabase {
            get {
                return ResourceManager.GetString("FixturesDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixtures workspace.
        /// </summary>
        public static string FixturesWorkspace {
            get {
                return ResourceManager.GetString("FixturesWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Pitch.
        /// </summary>
        public static string FlightPitch {
            get {
                return ResourceManager.GetString("FlightPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to settings and connect to database.
        /// </summary>
        public static string GoToSettingsAndConnectToDatabase {
            get {
                return ResourceManager.GetString("GoToSettingsAndConnectToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        public static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string InstructionContent_Date {
            get {
                return ResourceManager.GetString("InstructionContent_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction Data.
        /// </summary>
        public static string InstructionData {
            get {
                return ResourceManager.GetString("InstructionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change language: Save settings &amp; reload app.
        /// </summary>
        public static string LanguageChangeInfo {
            get {
                return ResourceManager.GetString("LanguageChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large End.
        /// </summary>
        public static string LargeEnd {
            get {
                return ResourceManager.GetString("LargeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenght (TL).
        /// </summary>
        public static string LenghtTL {
            get {
                return ResourceManager.GetString("LenghtTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load All.
        /// </summary>
        public static string LoadAll {
            get {
                return ResourceManager.GetString("LoadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading configuration file.
        /// </summary>
        public static string LoadingConfigurationFile {
            get {
                return ResourceManager.GetString("LoadingConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Fixture filters.
        /// </summary>
        public static string LoadingFixtureFilters {
            get {
                return ResourceManager.GetString("LoadingFixtureFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading materials.
        /// </summary>
        public static string LoadingMaterials {
            get {
                return ResourceManager.GetString("LoadingMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading module programs.
        /// </summary>
        public static string LoadingModulePrograms {
            get {
                return ResourceManager.GetString("LoadingModulePrograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading module types.
        /// </summary>
        public static string LoadingModuleTypes {
            get {
                return ResourceManager.GetString("LoadingModuleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading drawing preview.
        /// </summary>
        public static string LoadingPdfPreview {
            get {
                return ResourceManager.GetString("LoadingPdfPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine diameter.
        /// </summary>
        public static string MachineDiameter {
            get {
                return ResourceManager.GetString("MachineDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main angel.
        /// </summary>
        public static string MainAngel {
            get {
                return ResourceManager.GetString("MainAngel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Number.
        /// </summary>
        public static string ModuleNumber {
            get {
                return ResourceManager.GetString("ModuleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Revision.
        /// </summary>
        public static string ModuleRevision {
            get {
                return ResourceManager.GetString("ModuleRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module type.
        /// </summary>
        public static string ModuleType {
            get {
                return ResourceManager.GetString("ModuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Type.
        /// </summary>
        public static string NewInstructionDialog_ModuleType {
            get {
                return ResourceManager.GetString("NewInstructionDialog_ModuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select wear protection.
        /// </summary>
        public static string NoWearProtectionSelected {
            get {
                return ResourceManager.GetString("NoWearProtectionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Conveyor Module.
        /// </summary>
        public static string NumberConveyorModule {
            get {
                return ResourceManager.GetString("NumberConveyorModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select nc program.
        /// </summary>
        public static string OpenFileNcProgram {
            get {
                return ResourceManager.GetString("OpenFileNcProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PDF.
        /// </summary>
        public static string OpenPDF {
            get {
                return ResourceManager.GetString("OpenPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation number.
        /// </summary>
        public static string OperationNumber {
            get {
                return ResourceManager.GetString("OperationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside Diameter.
        /// </summary>
        public static string OutsideDiameter {
            get {
                return ResourceManager.GetString("OutsideDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall diameter.
        /// </summary>
        public static string OverallDiameter {
            get {
                return ResourceManager.GetString("OverallDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        public static string Parts {
            get {
                return ResourceManager.GetString("Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch.
        /// </summary>
        public static string Pitch {
            get {
                return ResourceManager.GetString("Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Date.
        /// </summary>
        public static string ProgramDate {
            get {
                return ResourceManager.GetString("ProgramDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer.
        /// </summary>
        public static string Programmer {
            get {
                return ResourceManager.GetString("Programmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program number.
        /// </summary>
        public static string ProgramNumber {
            get {
                return ResourceManager.GetString("ProgramNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save current progress?.
        /// </summary>
        public static string ProgressSave {
            get {
                return ResourceManager.GetString("ProgressSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Database.
        /// </summary>
        public static string ReloadDatabase {
            get {
                return ResourceManager.GetString("ReloadDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload descriptions.
        /// </summary>
        public static string ReloadDescriptions {
            get {
                return ResourceManager.GetString("ReloadDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload fixtures.
        /// </summary>
        public static string ReloadFixtures {
            get {
                return ResourceManager.GetString("ReloadFixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading tools.
        /// </summary>
        public static string ReloadingTools {
            get {
                return ResourceManager.GetString("ReloadingTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Item.
        /// </summary>
        public static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing.
        /// </summary>
        public static string Removing {
            get {
                return ResourceManager.GetString("Removing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing items.
        /// </summary>
        public static string RemovingItems {
            get {
                return ResourceManager.GetString("RemovingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing word file.
        /// </summary>
        public static string RemovingWordFile {
            get {
                return ResourceManager.GetString("RemovingWordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring settings.
        /// </summary>
        public static string RestoringSettings {
            get {
                return ResourceManager.GetString("RestoringSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or open instruction to save it.
        /// </summary>
        public static string SaveInfo {
            get {
                return ResourceManager.GetString("SaveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Instruction.
        /// </summary>
        public static string SaveInstruction {
            get {
                return ResourceManager.GetString("SaveInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving settings.
        /// </summary>
        public static string SavingSettings {
            get {
                return ResourceManager.GetString("SavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select cimco program.
        /// </summary>
        public static string SelectCimcoProgram {
            get {
                return ResourceManager.GetString("SelectCimcoProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select configuration file.
        /// </summary>
        public static string SelectConfigurationFile {
            get {
                return ResourceManager.GetString("SelectConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Description.
        /// </summary>
        public static string SelectDescription {
            get {
                return ResourceManager.GetString("SelectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select DXF.
        /// </summary>
        public static string SelectDXF {
            get {
                return ResourceManager.GetString("SelectDXF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select fixture drawing.
        /// </summary>
        public static string SelectFixtureDrawing {
            get {
                return ResourceManager.GetString("SelectFixtureDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Fixtures.
        /// </summary>
        public static string SelectFixtures {
            get {
                return ResourceManager.GetString("SelectFixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select just one item.
        /// </summary>
        public static string SelectJustOneItem {
            get {
                return ResourceManager.GetString("SelectJustOneItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language and restart app.
        /// </summary>
        public static string SelectLanguageAndRestartApp {
            get {
                return ResourceManager.GetString("SelectLanguageAndRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tools.
        /// </summary>
        public static string SelectTools {
            get {
                return ResourceManager.GetString("SelectTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select word file.
        /// </summary>
        public static string SelectWordFile {
            get {
                return ResourceManager.GetString("SelectWordFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        public static string SettingsView_AppTheme {
            get {
                return ResourceManager.GetString("SettingsView_AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed tools.
        /// </summary>
        public static string SettingsView_DetailedTools {
            get {
                return ResourceManager.GetString("SettingsView_DetailedTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to generate detailed tool list.
        /// </summary>
        public static string SettingsView_EnableToGenerateDetaildToolList {
            get {
                return ResourceManager.GetString("SettingsView_EnableToGenerateDetaildToolList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter values to change window size.
        /// </summary>
        public static string SettingsView_EnterValuesToChangeWindowSize {
            get {
                return ResourceManager.GetString("SettingsView_EnterValuesToChangeWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which app theme to display.
        /// </summary>
        public static string SettingsView_SelectWhichAppThemToDisplay {
            get {
                return ResourceManager.GetString("SettingsView_SelectWhichAppThemToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window size.
        /// </summary>
        public static string SettingsView_WindowSize {
            get {
                return ResourceManager.GetString("SettingsView_WindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small End.
        /// </summary>
        public static string SmallEnd {
            get {
                return ResourceManager.GetString("SmallEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub angel.
        /// </summary>
        public static string SubAngel {
            get {
                return ResourceManager.GetString("SubAngel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taper.
        /// </summary>
        public static string Taper {
            get {
                return ResourceManager.GetString("Taper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Instructions.
        /// </summary>
        public static string TaskGenerating {
            get {
                return ResourceManager.GetString("TaskGenerating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool list.
        /// </summary>
        public static string ToolList {
            get {
                return ResourceManager.GetString("ToolList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Records:.
        /// </summary>
        public static string TotalRecords {
            get {
                return ResourceManager.GetString("TotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        public static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating .
        /// </summary>
        public static string UpdatingItem {
            get {
                return ResourceManager.GetString("UpdatingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        public static string Variables {
            get {
                return ResourceManager.GetString("Variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create or Open instruction to add new nc program.
        /// </summary>
        public static string WarningDropNcProgram {
            get {
                return ResourceManager.GetString("WarningDropNcProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format.
        /// </summary>
        public static string WarningFileLoad {
            get {
                return ResourceManager.GetString("WarningFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wear Protection.
        /// </summary>
        public static string WearProtection {
            get {
                return ResourceManager.GetString("WearProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Size.
        /// </summary>
        public static string WindowSize {
            get {
                return ResourceManager.GetString("WindowSize", resourceCulture);
            }
        }
    }
}
